<a href="https://colab.research.google.com/github/herusy/Machine_Learning/blob/main/%D0%93%D0%B5%D1%80%D1%83%D1%81_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 1
Герус Ярослав ФІТ 4-8
Варіант 6

*Створіть одновимірний масив (вектор) з перших 10-ти додатних парних чисел та
виведіть його значення.*


In [1]:
import numpy as np

even_numbers = np.arange(2, 21, 2)
print(even_numbers)


[ 2  4  6  8 10 12 14 16 18 20]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його сумою кожного
числа та його попереднього, починаючи з 1, та виведіть його значення.

In [2]:
matrix = np.array([[1 + 0, 2 + 1, 3 + 2],
                   [4 + 3, 5 + 4, 6 + 5],
                   [7 + 6, 8 + 7, 9 + 8]])

matrix

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Створіть масив розміром 2x3, заповніть його випадковими цілими числами в діапазоні
від -1 до 1 та виведіть його значення.

In [3]:
import numpy as np

array = np.random.randint(-1, 2, size=(2, 3))

print(array)


[[-1  1  1]
 [-1  1  1]]


Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного
рядка матриці.

In [4]:
import numpy as np

array = np.random.rand(5, 5)

row_sums = np.sum(array, axis=1).reshape(-1, 1)

print(array)
print(row_sums)


[[0.76733935 0.85034722 0.51237753 0.82992777 0.84345766]
 [0.65722126 0.80068233 0.99742365 0.84479945 0.62477639]
 [0.20810307 0.1562086  0.0604939  0.96311029 0.46441728]
 [0.32984272 0.82287471 0.45314308 0.32540627 0.33903634]
 [0.90461106 0.52874743 0.93961958 0.43681194 0.0193764 ]]
[[3.80344954]
 [3.92490309]
 [1.85233315]
 [2.27030311]
 [2.82916641]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими дійсними
числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та
множення.


In [5]:
import numpy as np

array1 = np.random.rand(5)
array2 = np.random.rand(5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)


Array 1: [0.71954015 0.64666092 0.01502736 0.49547948 0.42599533]
Array 2: [0.10827666 0.18631715 0.54222127 0.76833239 0.32414612]
Addition: [0.82781681 0.83297806 0.55724863 1.26381187 0.75014145]
Subtraction: [ 0.61126349  0.46034377 -0.5271939  -0.27285291  0.10184922]
Multiplication: [0.0779094  0.12048402 0.00814816 0.38069293 0.13808473]


Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 5 до 30 та
знайдіть їх добуток.

In [6]:
import numpy as np

matrix1 = np.random.uniform(5, 30, (3, 3))
matrix2 = np.random.uniform(5, 30, (3, 3))

product = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Product:\n", product)


Matrix 1:
 [[ 9.89916448 19.94066964 24.19930419]
 [19.52845176 17.32195428 12.23385556]
 [18.6489964  13.95893061 22.95379813]]
Matrix 2:
 [[24.43029982  5.36597831 27.60739756]
 [25.99762156  9.37320465 25.80622664]
 [21.01850613 19.13460492 15.67663446]]
Product:
 [[1268.88276239  703.07080424 1167.24725529]
 [1184.55291168  501.24146367 1177.92969123]
 [1300.95411548  670.1218821  1234.91588759]]


Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.


In [7]:
import numpy as np

matrix1 = np.random.randint(1, 6, (2, 3))
matrix2 = np.random.randint(1, 6, (3, 4))

product = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Product:\n", product)


Matrix 1:
 [[2 3 3]
 [3 1 1]]
Matrix 2:
 [[1 2 3 1]
 [4 2 4 1]
 [2 2 4 1]]
Product:
 [[20 16 30  8]
 [ 9 10 17  5]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 8 та знайдіть її обернену матрицю.

In [8]:
import numpy as np

matrix = np.random.randint(1, 9, (3, 3))
inverse_matrix = np.linalg.inv(matrix)

print("Matrix:\n", matrix)
print("Inverse Matrix:\n", inverse_matrix)


Matrix:
 [[8 1 6]
 [4 7 1]
 [2 5 8]]
Inverse Matrix:
 [[ 0.12318841  0.0531401  -0.09903382]
 [-0.07246377  0.12560386  0.03864734]
 [ 0.01449275 -0.09178744  0.12560386]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.

In [9]:
import numpy as np

matrix = np.random.rand(4, 4)
transposed_matrix = matrix.T

print("Matrix:\n", matrix)
print("Transposed Matrix:\n", transposed_matrix)


Matrix:
 [[0.48723629 0.70185542 0.41406392 0.9081195 ]
 [0.31643859 0.30388344 0.41958363 0.75297003]
 [0.74033364 0.36998872 0.19449553 0.17453214]
 [0.46191649 0.42193653 0.14981099 0.78174007]]
Transposed Matrix:
 [[0.48723629 0.31643859 0.74033364 0.46191649]
 [0.70185542 0.30388344 0.36998872 0.42193653]
 [0.41406392 0.41958363 0.19449553 0.14981099]
 [0.9081195  0.75297003 0.17453214 0.78174007]]


Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, знайдіть добуток матриці на вектор.

In [10]:
import numpy as np

matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)

product = np.dot(matrix, vector)

print("Matrix:\n", matrix)
print("Vector:\n", vector)
print("Product:\n", product)


Matrix:
 [[0.95717847 0.82655462 0.10790319 0.20899608]
 [0.18317883 0.56911878 0.88849687 0.8804123 ]
 [0.21663283 0.78525377 0.87159045 0.57805911]]
Vector:
 [[0.57637007]
 [0.964252  ]
 [0.7559661 ]
 [0.48923688]]
Product:
 [[1.53251572]
 [1.7567564 ]
 [1.82374387]]


Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [11]:
import numpy as np

matrix = np.random.randint(1, 11, (2, 3))
vector = np.random.rand(3, 1)

product = np.dot(matrix, vector)

print("Matrix:\n", matrix)
print("Vector:\n", vector)
print("Product:\n", product)


Matrix:
 [[2 5 8]
 [1 6 7]]
Vector:
 [[0.4548792 ]
 [0.99206038]
 [0.06217763]]
Product:
 [[6.36748135]
 [6.8424849 ]]


Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню різницю.


In [12]:
import numpy as np

matrix1 = np.random.randint(1, 11, (7, 7))
matrix2 = np.random.randint(1, 11, (7, 7))

difference = matrix1 - matrix2

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Difference:\n", difference)


Matrix 1:
 [[ 9  2  5  3 10  3  5]
 [ 9  2  7  8 10  8  7]
 [ 4  8  7  1  2  3  1]
 [ 9 10  4  3  6  5  8]
 [ 5  4  9  9  6  5  8]
 [ 2  7  6  4  7  3  7]
 [ 1  9 10  3  6  3  7]]
Matrix 2:
 [[ 9  3  6 10  2 10  6]
 [ 6  6 10  2  7  1  1]
 [ 3  3  1  1 10  9  1]
 [ 6  7  1  8  6  5 10]
 [ 6  4  8  3  6  7  3]
 [10  5  4  8  5  6  9]
 [ 6  1  3  9  9  8  7]]
Difference:
 [[ 0 -1 -1 -7  8 -7 -1]
 [ 3 -4 -3  6  3  7  6]
 [ 1  5  6  0 -8 -6  0]
 [ 3  3  3 -5  0  0 -2]
 [-1  0  1  6  0 -2  5]
 [-8  2  2 -4  2 -3 -2]
 [-5  8  7 -6 -3 -5  0]]


Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в
діапазоні від -10 до 10 та знайдіть суму їх елементів.

In [14]:
import numpy as np

matrix1 = np.random.randint(-10, 11, (7, 7))
matrix2 = np.random.randint(-10, 11, (7, 7))

sum_of_elements = np.sum(matrix1) + np.sum(matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Sum of elements:", sum_of_elements)



Matrix 1:
 [[-10  -3   4  -9  -4  -2 -10]
 [ -4   4   1  -3  -9   4  10]
 [  3  -5   7   2   0 -10   9]
 [  5   9   5  -1   7  -5   9]
 [  1   5  10  -3   2  10   7]
 [ -3   4  -9  -7  -8   2  -1]
 [  2   3  -6   1   4  -3   5]]
Matrix 2:
 [[  8   7   3   1  10   5  -4]
 [  6   1  -6   8   5   8  -7]
 [-10  -6   2   6   5   6  -4]
 [  1   0   9  -7   7  -6  10]
 [ -8  -6   8 -10  -4  -5  -7]
 [  1   9  -9  -3   6   6   4]
 [ -5  -6   7   6   3   5  -2]]
Sum of elements: 68


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть середнє арифметичне значення елементів матриці.

In [15]:
import numpy as np

matrix = np.random.randint(1, 11, (3, 3))
mean_value = np.mean(matrix)

print("Matrix:\n", matrix)
print("Mean value:", mean_value)


Matrix:
 [[ 9  3  5]
 [ 6  4 10]
 [ 9  4  6]]
Mean value: 6.222222222222222


Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найменший елемент у
кожному рядку матриці.

In [16]:
import numpy as np

matrix = np.random.uniform(-1, 1, (8, 8))
min_elements = np.min(matrix, axis=1).reshape(-1, 1)

print("Matrix:\n", matrix)
print("Column vector of minimum elements:\n", min_elements)


Matrix:
 [[-0.57093995  0.9396601  -0.4472823   0.61675679 -0.27817695 -0.04955463
  -0.0647473   0.33322399]
 [-0.99106943  0.89443601  0.17895789 -0.17424324  0.83227028  0.93317469
   0.77384371  0.71223188]
 [-0.98271107 -0.7436523   0.58985279  0.37044008  0.02419235  0.27323714
   0.72548909 -0.49330241]
 [ 0.78033195  0.95010786  0.62834391  0.14320539 -0.17711961  0.88347063
  -0.2772651  -0.28450177]
 [-0.22208258 -0.27759031 -0.48868059 -0.75932412  0.67640536  0.5523497
   0.24934214  0.57726273]
 [ 0.8054401  -0.87831655  0.85537084  0.01439018 -0.3512005  -0.32443025
   0.02729303 -0.73302411]
 [-0.62358337  0.9976523   0.47459066  0.56685638  0.24295374 -0.35845887
   0.97458335 -0.81364573]
 [-0.6103255   0.30944519  0.9613293   0.75086881  0.47325698  0.12924931
   0.88206723  0.6810885 ]]
Column vector of minimum elements:
 [[-0.57093995]
 [-0.99106943]
 [-0.98271107]
 [-0.28450177]
 [-0.75932412]
 [-0.87831655]
 [-0.81364573]
 [-0.6103255 ]]


Висновок: навчився робити завдання з масивами