<a href="https://colab.research.google.com/github/herusy/Machine_Learning/blob/main/%D0%93%D0%B5%D1%80%D1%83%D1%81_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Герус Ярослав ФІТ 4-8 Варіант 6

In [ ]:
import numpy as np

In [ ]:
#1 Створіть одновимірний масив (вектор) з числами Фібоначчі, де кожне число дорівнює сумі двох попередніх, та виведіть його значення.
def fibonacci_arr(n):
    fib_arr = np.zeros(n, dtype=int)
    fib_arr[0] = 0
    if n > 1:
        fib_arr[1] = 1
        for i in range(2, n):
            fib_arr[i] = fib_arr[i-1] + fib_arr[i-2]
    return fib_arr

n = 10
fib_arr = fibonacci_arr(n)
print(fib_arr)


[ 0  1  1  2  3  5  8 13 21 34]


In [ ]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями експонент n^2 для кожного натурального числа n,
# починаючи з 1, та виведіть його значення.
def matrix(n):
    arr1 = np.arange(1, 10)
    arr1 = arr1 ** 2
    matrix = arr1.reshape(3, 3)

    return matrix

arr1 = matrix(n)
print(arr1)


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
#3 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до 1 та виведіть його значення.
matrix = np.random.rand(3, 3)
matrix = 2 * matrix - 1
print(matrix)

[[-0.44262578 -0.82538776 -0.93102061]
 [-0.72409307 -0.93531834  0.26607328]
 [-0.27790975 -0.15430026  0.75013428]]


In [ ]:
#4 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів.

matrix = np.random.rand(3, 3)
product = 1
n = 0

for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        product *= matrix[i, j]
        n += 1

geometric_mean = product ** (1 / n)

print("Matrix:\n", matrix)
print("\nGeometric Mean:\n", geometric_mean)


Matrix:
 [[0.12742317 0.89110534 0.01589967]
 [0.24352503 0.50529157 0.16422945]
 [0.58605763 0.53580777 0.3655832 ]]

Geometric Mean:
 0.2526088901363246


In [ ]:
#5 Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними
# числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання
# та множення.

arr1 = np.random.rand(6) * 10 - 5
arr2 = np.random.rand(6) * 10 - 5

sum_result = arr1 + arr2
difference_result = arr1 - arr2
product_result = arr1 * arr2

print("arr1 =", arr1)
print("\narr2 =", arr2)
print("\nSum of elements =", sum_result)
print("\nDifference of elements =", difference_result)
print("\nProduct of elements =", product_result)

arr1 = [-2.29424305 -0.58329185  3.10636726  2.89602653 -2.28417096  2.65263375]

arr2 = [-0.38518836  4.82254829 -0.66590992  2.56598166 -4.22841869  3.63028572]

Sum of elements = [-2.67943141  4.23925645  2.44045734  5.46200819 -6.51258965  6.28291947]

Difference of elements = [-1.90905469 -5.40584014  3.77227718  0.33004486  1.94424774 -0.97765197]

Product of elements = [ 0.88371572 -2.81295309 -2.06856078  7.43115096  9.65843117  9.62981841]


In [ ]:
#6 Створіть дві матриці 5x5, заповніть їх довільними цілими числами від 1 до 10 та
# знайдіть їх добуток.

matrix1 = np.random.randint(1, 11, (5, 5))
matrix2 = np.random.randint(1, 11, (5, 5))

result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2:\n", result)

Matrix 1:
 [[ 9  4  8  1  2]
 [ 7  4  5  5  1]
 [ 4  3  9  2  2]
 [ 2  5  8  5  6]
 [10  8  9  3 10]]

Matrix 2:
 [[ 5  7  3  9  7]
 [ 2  5  4 10  1]
 [ 9  6  1  1  6]
 [ 1  5  8  4  1]
 [ 4  5  7 10 10]]

Product of Matrix 1 and Matrix 2:
 [[134 146  73 153 136]
 [ 97 129  89 138  98]
 [117 117  63 103 107]
 [121 142 116 156 132]
 [190 229 165 291 235]]


In [ ]:
#7 Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 10 та перемножте їх між собою.

matrix1 = np.random.randint(1, 11, (3, 2))
matrix2 = np.random.randint(1, 11, (2, 4))

result = np.dot(matrix1, matrix2)

print("Matrix 1 (3x2):\n", matrix1)
print("\nMatrix 2 (2x4):\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2 (3x4):\n", result)


Matrix 1 (3x2):
 [[ 7  2]
 [ 2 10]
 [ 4  5]]

Matrix 2 (2x4):
 [[9 7 1 5]
 [4 6 2 8]]

Product of Matrix 1 and Matrix 2 (3x4):
 [[71 61 11 51]
 [58 74 22 90]
 [56 58 14 60]]


In [ ]:
#8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
# від 1 до 15 та знайдіть її обернену матрицю.

matrix = np.random.randint(1, 16, (2, 2))

inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix (2x2):\n", matrix)
print("\nInverse Matrix (2x2):\n", inverse_matrix)


Original Matrix (2x2):
 [[ 6  1]
 [15 10]]

Inverse Matrix (2x2):
 [[ 0.22222222 -0.02222222]
 [-0.33333333  0.13333333]]


In [ ]:
#9 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від 7 до 15 та транспонуйте її.

matrix = np.random.randint(7, 16, (3, 3))

transposed_matrix = np.transpose(matrix)

print("Original Matrix (3x3):\n", matrix)
print("\nTransposed Matrix (3x3):\n", transposed_matrix)


Original Matrix (3x3):
 [[14  8 13]
 [ 7  8  9]
 [13 10 12]]

Transposed Matrix (3x3):
 [[14  7 13]
 [ 8  8 10]
 [13  9 12]]


In [ ]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10 і знайдіть добуток матриці на вектор.

matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, (4, 1))

result = np.dot(matrix, vector)

print("Matrix (3x4):\n", matrix)
print("\nVector (4x1):\n", vector)
print("\nProduct of Matrix and Vector:\n", result)


Matrix (3x4):
 [[0.38028674 0.18527166 0.9686078  0.26763797]
 [0.21018496 0.11421828 0.13676129 0.48646612]
 [0.4256444  0.34653252 0.51595912 0.8585871 ]]

Vector (4x1):
 [[2]
 [5]
 [5]
 [9]]

Product of Matrix and Vector:
 [[ 8.93871255]
 [ 6.05346282]
 [12.89103088]]


In [ ]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, (3, 1))

result = np.dot(matrix, vector)

print("Matrix (2x3):\n", matrix)
print("\nVector (3x1):\n", vector)
print("\nProduct of Matrix and Vector:\n", result)


NameError: name 'np' is not defined

In [ ]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

total_sum = np.sum(matrix1) + np.sum(matrix2)

print("Matrix 1 (2x2):\n", matrix1)
print("\nMatrix 2 (2x2):\n", matrix2)
print("\nSum of all elements in both matrices:\n", total_sum)


Matrix 1 (2x2):
 [[ 5  8]
 [10  9]]

Matrix 2 (2x2):
 [[ 8 10]
 [ 7 10]]

Sum of all elements in both matrices:
 67


In [ ]:
#13 Створіть дві матриці розміром 10x10, заповніть їх випадковими дійсними числами в
# діапазоні від -2 до 2 та знайдіть їх добуток.

matrix1 = np.random.uniform(-2, 2, (10, 10))
matrix2 = np.random.uniform(-2, 2, (10, 10))

product_matrix = np.dot(matrix1, matrix2)

print("Matrix 1 (10x10):\n", matrix1)
print("\nMatrix 2 (10x10):\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2 (10x10):\n", product_matrix)


Matrix 1 (10x10):
 [[ 0.93300081 -1.59658492 -0.23131254  0.07584245  1.98936517  0.12924717
  -0.87226979  1.42092983 -0.93042539 -1.30334385]
 [ 1.21714602  0.18782719 -0.92973728 -0.97957572 -0.16040918 -0.62068424
   1.80081446  0.30766441  1.6061403  -0.65636468]
 [ 0.69738191 -1.98311731  1.78449398 -0.46036518 -1.62135413  1.0733264
   0.53986222 -1.0350555  -0.54848681 -1.28392478]
 [-0.25594093 -1.03687577  1.46627328 -0.51317878  1.23107394  0.21383286
  -1.37984281 -1.71945644 -1.66871312 -1.1112497 ]
 [ 1.79789751  1.71841654  0.17961761  0.09119954  1.96600901 -1.43907618
  -1.40890412 -1.66762922 -0.69336506  0.6662673 ]
 [ 0.49708949 -0.77741908  1.67817467 -0.27543575  0.6446425   1.0197441
   0.3815836   1.99951828 -0.44167036  0.91614221]
 [ 0.34701373 -0.13206793  0.24668057 -1.79020436 -0.97952671 -1.66295651
   1.30501681  0.56464634  0.44538149 -1.76486031]
 [-0.66639278 -1.62870595 -1.21521349  0.94731316  1.24471082  0.88243093
  -0.52458255 -1.67966299  0.12390

In [ ]:
#14 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -1 до 1 та знайдіть середнє арифметичне значення елементів матриці.

matrix = np.random.uniform(-1, 1, (3, 3))

average_value = np.mean(matrix)

print("Matrix (3x3):\n", matrix)
print("\nAverage value of the elements in the matrix:\n", average_value)


Matrix (3x3):
 [[ 0.12013412 -0.52719621 -0.3202398 ]
 [-0.49751812 -0.93415102  0.41665462]
 [-0.37152128  0.71583601  0.89839717]]

Average value of the elements in the matrix:
 -0.05551161239464185


In [ ]:
#15 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
# що містить суму квадратів елементів кожного рядка матриці

matrix = np.random.uniform(0, 1, (3, 3))

sum_of_squares = np.sum(matrix**2, axis=1)
column_vector = sum_of_squares[:, np.newaxis]

print("Matrix (3x3):\n", matrix)
print("\nColumn vector with sum of squares of each row:\n", column_vector)


Matrix (3x3):
 [[0.90294999 0.57218408 0.15288324]
 [0.26852061 0.0254162  0.41923106]
 [0.2117935  0.88423073 0.42706899]]

Column vector with sum of squares of each row:
 [[1.1660866 ]
 [0.24850398]
 [1.00910839]]


In [ ]:
# Висновок: виконавши дану лабораторну роботу, освоїла методи та дії над матрицями.